### ISSUE TITLE
在最新ng-alain中运行报错 NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by xiaohuilam** [cipchk/ng-deploy-oss#15]
环境：
```
"@angular/core": "~13.1.1",
"ng-alain": "^13.0.0",
```

```
git:(master) node -v
v17.2.0
```

```
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/Users/xiaohuilam/Project/nginx/ca/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/Users/xiaohuilam/Project/nginx/ca/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /Users/xiaohuilam/Project/nginx/ca/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/Users/xiaohuilam/Project/nginx/ca/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/xiaohuilam/Project/nginx/ca/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/Users/xiaohuilam/Project/nginx/ca/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/Users/xiaohuilam/Project/nginx/ca/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /Users/xiaohuilam/Project/nginx/ca/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/Users/xiaohuilam/Project/nginx/ca/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/xiaohuilam/Project/nginx/ca/node_modules/ajv/dist/compile/codegen/index.js:568:18)
```

**Comment by cipchk** [comment]
fixed by `13.0.0`
